tps = 5
cell_margin = 0.1
camera_margin = 2

[colors]
background = "black"
player = "red"
snake_head = "green"
snake_tail = "#030"
snake = ["#070", "#060", "#050", "#040", "#050", "#060"]
wall = "white"
hovered = "#7777"
