player_speed = 10
snake_speed = 10
new_item_time = 1
cell_margin = 0.1
camera_margin = 2
snake_vision = 10
start_snake_size = 5
food_value = 2
time_scale = 1
max_items = 10

[items.snake_speed]
time = 5
multiplier = 2

[weights]
food = 70
reverse = 10
snake_speed_up = 5
snake_speed_down = 10
snake_split = 5

[colors]
background = "black"
player = "red"
food = "#f7a"
snake_head = "green"
snake_tail = "#030"
snake = ["#070", "#060", "#050", "#040", "#050", "#060"]
wall = "white"
hovered = "#7777"
snake_vision = "#f003"
reverse = "blue"
snake_speed_up = "#70f"
snake_speed_down = "#307"
snake_split = "yellow"

[controls]
use_item = ["Space", "Enter"]
left = ["A", "ArrowLeft"]
right = ["D", "ArrowRight"]
up = ["W", "ArrowUp"]
down = ["S", "ArrowDown"]
