player_speed = 10
snake_speed = 10
new_item_time = 1
cell_margin = 0.1
camera_margin = 4
snake_vision = 1000000
start_snake_size = 5
food_value = 2
time_scale = 1
max_items = 10
snake_wake_up_time = 1
snake_reverse_speed = 25
text_scale = 1
ui_fov = 10
particle_opacity = 0.5
particle_size = 1
particle_max_speed = 3
particle_amount = 3
particle_lifetime = 0.5
volume = 1
music_volume = 0.5
outline_size = 0.07
outline_color = "#010"

[items.snake_speed]
time = 5
multiplier = 1.5

[weights]
food = 200
reverse = 10
snake_speed_up = 5
snake_speed_down = 10
snake_split = 10

[colors]
background = "#010"
player = "red"
food = "#f7a"
snake_head = "green"
snake_tail = "#030"
snake = ["#070", "#060", "#050", "#040", "#050", "#060"]
wall = "#aaa"
hovered = "#7777"
snake_vision = "#f003"
reverse = "blue"
snake_speed_up = "#70f"
snake_speed_down = "#307"
snake_split = "yellow"

[controls]
use_item = ["Space", "Enter"]
left = ["A", "ArrowLeft"]
right = ["D", "ArrowRight"]
up = ["W", "ArrowUp"]
down = ["S", "ArrowDown"]
