player_speed = 3
snake_speed = 5
new_item_time = 2
cell_margin = 0.1
camera_margin = 2
snake_vision = 5

[items.snake_speed]
time = 5
multiplier = 2

[weights]
food = 70
reverse = 10
snake_speed_up = 10
snake_speed_down = 10

[colors]
background = "black"
player = "red"
food = "#f7a"
snake_head = "green"
snake_tail = "#030"
snake = ["#070", "#060", "#050", "#040", "#050", "#060"]
wall = "white"
hovered = "#7777"
snake_vision = "#f003"
reverse = "blue"
snake_speed_up = "#70f"
snake_speed_down = "#307"

[controls]
use_item = ["Space", "Enter"]
left = ["A", "ArrowLeft"]
right = ["D", "ArrowRight"]
up = ["W", "ArrowUp"]
down = ["S", "ArrowDown"]
